name: directory list
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Append directory tree to README
        run: |
          sudo apt-get install tree
          sudo rm -rf README.md
          touch README.md
          git add README.md
          echo "# My daily note    " > README.md
          
          # Fetch open issues
          echo "Fetching open issues..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open" \
            | jq -r '.[] | .title' > open_issues.txt
  
          # Fetch closed issues
          echo "Fetching closed issues..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=closed" \
            | jq -r '.[] | .title' > closed_issues.txt
  
          # Create a temporary file with the updated README content
          echo "# Issue List" >> README.md
          echo "" >> README.md
          echo "## Open Issues" >> updated_readme.md
          cat open_issues.txt | sed 's/^/- /' >> README.md
          echo "" >>README.md
          echo "## Closed Issues" >> README.md
          cat closed_issues.txt | sed 's/^/- /' >> README.md
          echo "" >> README.md
#          echo -e "![main](./.images/main.jpg)    \n" >> README.md

          tree --dirsfirst --noreport -I README.md | sed 's/^/    /' >> README.md
      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update README with directory list"
          git push origin main