name: directory list
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Append directory tree to README
        run: |
          sudo apt-get install tree
          tree --dirsfirst --noreport -I README.md | sed 's/^/    /' > README.md
      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update README with directory list"
          git push origin main